### ISSUE TITLE
Lines only added to memory when pressing up arrow.

### ISSUE THREAD

**Issue by sancarn** [TarVK/chromeConsole#4]
Odd bug. I noticed it here: https://youtu.be/oX44CQpsk9M?t=197 at 3:24

Ultimately I lost what I typed and it wasn't saved in memory so I had to retype it.

After some discussion with @TarVK it seems that it only pushes to memory when hitting arrow up, but if you hit arrow down and never hit up before, it isn't in memory

**Comment by TarVK** [comment]
This issue got resolved when fixing history related issues: https://github.com/TarVK/chromeConsole/commit/8b6c072f11a1dc100c4d6f7b772dbd2ced4103a9
