### ISSUE TITLE
Fix command duplication in memory

### ISSUE THREAD

**Issue by sancarn** [TarVK/chromeConsole#6]
If you run the same command over and over in memory then the same command is also added to memory each time. E.G.
```
console.log("hello world")
console.log("a")
console.log("a")
console.log("a")
```

Running these commands in sequence (not all together) will mean that you have to press the `up` key 4 times to get back to `console.log("hello world")`.

Chrome's console actually only adds a command to the memory buffer if it isn't identical to the last element in memory. E.G. The memory for:

```
console.log("a")
console.log("b")
console.log("a")
console.log("a")
console.log("a")
```

Will look like this:

```
console.log("a")
console.log("b")
console.log("a")
```

**Comment by TarVK** [comment]
Should be fixed with the changes in this branch: [issue-history](https://github.com/TarVK/chromeConsole/tree/issue-history)
